services:
  php:
    env_file:
      - .env
    build: ./docker/php
    volumes:
      - .:/var/www/phonolang

  web:
    env_file:
      - .env
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - .:/var/www/phonolang
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/phonolang

  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - "5432:5432"

volumes:
  db-store:
