services:
  php:
    env_file:
      - .env
    build: ./docker/php
    volumes:
      - .:/var/www/phonolang

  web:
    env_file:
      - .env
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - .:/var/www/phonolang
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/phonolang
  db:
    env_file:
      - .env
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TZ}
    ports:
      - "3306:3306"

volumes:
  db-store:
